# Generated by Django 4.2.6 on 2023-10-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
