# Generated by Django 4.2.6 on 2023-10-19 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CustomUser", "0001_initial"),
        ("doctor", "0002_doctor_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="CustomUser.customuser"
            ),
        ),
    ]
