# Generated by Django 4.2.6 on 2023-10-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_time",
            field=models.BigIntegerField(),
        ),
    ]
