# Generated by Django 4.2.6 on 2023-12-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
