# Generated by Django 4.2.6 on 2023-10-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_patient_doctor_patient_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="name",
        ),
        migrations.AddField(
            model_name="patient",
            name="blood_group",
            field=models.CharField(default="Unknown", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="height",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="diagnoses",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medications",
            field=models.TextField(blank=True),
        ),
    ]
