# Generated by Django 4.2.7 on 2023-12-01 18:07

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnoses',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medications',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
    ]
